version: "3.8"
services:
  mssql:
    build: ./db
    platform: linux/amd64
    container_name: dacnpm_be
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db.bacpac:/var/opt/mssql/data/db.bacpac
      - ./data:/docker-entrypoint-initdb.d
    restart: always
